# -*- coding: utf-8 -*- 
"""Subclass of DialogAbout, which is generated by wxFormBuilder."""

import wx
import ui

import images
import version

# Implementing DialogAbout
class uiDialogAbout( ui.DialogAbout ):
	def __init__( self, parent ):
		ui.DialogAbout.__init__( self, parent )

		self.bitmapIcon.SetIcon(images.kindle128.GetIcon())
		self.staticText1.SetLabel(u'fb2conv {0}'.format(version.VERSION))
		self.Fit()
		self.CenterOnParent()
	
	# Handlers for DialogAbout events.
	def buttonOkOnClick( self, event ):
		self.EndModal(wx.ID_OK)
	
	
