# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 6, 6, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bookInfoSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.bookInfoSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.bookInfoSplitter.setChildrenCollapsible(False)
        self.bookInfoSplitter.setObjectName("bookInfoSplitter")
        self.treeFileList = QtWidgets.QTreeWidget(self.bookInfoSplitter)
        self.treeFileList.setAcceptDrops(False)
        self.treeFileList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.treeFileList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.treeFileList.setAlternatingRowColors(True)
        self.treeFileList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeFileList.setRootIsDecorated(False)
        self.treeFileList.setObjectName("treeFileList")
        self.treeFileList.header().setVisible(True)
        self.scrollBookInfo = QtWidgets.QScrollArea(self.bookInfoSplitter)
        self.scrollBookInfo.setWidgetResizable(True)
        self.scrollBookInfo.setObjectName("scrollBookInfo")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 501))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imgBookCover = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgBookCover.sizePolicy().hasHeightForWidth())
        self.imgBookCover.setSizePolicy(sizePolicy)
        self.imgBookCover.setMinimumSize(QtCore.QSize(120, 160))
        self.imgBookCover.setMaximumSize(QtCore.QSize(120, 160))
        self.imgBookCover.setBaseSize(QtCore.QSize(120, 160))
        self.imgBookCover.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgBookCover.setText("")
        self.imgBookCover.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBookCover.setObjectName("imgBookCover")
        self.horizontalLayout_2.addWidget(self.imgBookCover)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelAuthor = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelAuthor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.verticalLayout.addWidget(self.labelAuthor)
        self.editAuthor = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAuthor.sizePolicy().hasHeightForWidth())
        self.editAuthor.setSizePolicy(sizePolicy)
        self.editAuthor.setObjectName("editAuthor")
        self.verticalLayout.addWidget(self.editAuthor)
        self.labelBookTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBookTitle.setObjectName("labelBookTitle")
        self.verticalLayout.addWidget(self.labelBookTitle)
        self.editTitle = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.editTitle.setObjectName("editTitle")
        self.verticalLayout.addWidget(self.editTitle)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSeries = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelSeries.setObjectName("labelSeries")
        self.gridLayout_2.addWidget(self.labelSeries, 0, 0, 1, 1)
        self.labelSeriesNumber = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelSeriesNumber.setObjectName("labelSeriesNumber")
        self.gridLayout_2.addWidget(self.labelSeriesNumber, 0, 1, 1, 1)
        self.editSeries = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.editSeries.setObjectName("editSeries")
        self.gridLayout_2.addWidget(self.editSeries, 1, 0, 1, 1)
        self.editSeriesNumber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSeriesNumber.sizePolicy().hasHeightForWidth())
        self.editSeriesNumber.setSizePolicy(sizePolicy)
        self.editSeriesNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editSeriesNumber.setObjectName("editSeriesNumber")
        self.gridLayout_2.addWidget(self.editSeriesNumber, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboGenres = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboGenres.setObjectName("comboGenres")
        self.verticalLayout.addWidget(self.comboGenres)
        self.labelBookLanguage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBookLanguage.setObjectName("labelBookLanguage")
        self.verticalLayout.addWidget(self.labelBookLanguage)
        self.editBookLanguage = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.editBookLanguage.setObjectName("editBookLanguage")
        self.verticalLayout.addWidget(self.editBookLanguage)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.editTranslator = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.editTranslator.setObjectName("editTranslator")
        self.verticalLayout.addWidget(self.editTranslator)
        spacerItem1 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonSaveBookInfo = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSaveBookInfo.sizePolicy().hasHeightForWidth())
        self.buttonSaveBookInfo.setSizePolicy(sizePolicy)
        self.buttonSaveBookInfo.setObjectName("buttonSaveBookInfo")
        self.horizontalLayout.addWidget(self.buttonSaveBookInfo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollBookInfo.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.bookInfoSplitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddFile = QtWidgets.QAction(MainWindow)
        self.actionAddFile.setObjectName("actionAddFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenForumURL = QtWidgets.QAction(MainWindow)
        self.actionOpenForumURL.setObjectName("actionOpenForumURL")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionViewLog = QtWidgets.QAction(MainWindow)
        self.actionViewLog.setObjectName("actionViewLog")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setMenuRole(QtWidgets.QAction.PreferencesRole)
        self.actionSettings.setObjectName("actionSettings")
        self.toolAdd = QtWidgets.QAction(MainWindow)
        self.toolAdd.setObjectName("toolAdd")
        self.toolInfo = QtWidgets.QAction(MainWindow)
        self.toolInfo.setObjectName("toolInfo")
        self.toolSettings = QtWidgets.QAction(MainWindow)
        self.toolSettings.setObjectName("toolSettings")
        self.toolSaveToDisk = QtWidgets.QAction(MainWindow)
        self.toolSaveToDisk.setObjectName("toolSaveToDisk")
        self.toolSendToKindle = QtWidgets.QAction(MainWindow)
        self.toolSendToKindle.setObjectName("toolSendToKindle")
        self.toolSendMail = QtWidgets.QAction(MainWindow)
        self.toolSendMail.setObjectName("toolSendMail")
        self.actionConvertToDisk = QtWidgets.QAction(MainWindow)
        self.actionConvertToDisk.setObjectName("actionConvertToDisk")
        self.actionSendToKindle = QtWidgets.QAction(MainWindow)
        self.actionSendToKindle.setObjectName("actionSendToKindle")
        self.actionSendViaMail = QtWidgets.QAction(MainWindow)
        self.actionSendViaMail.setObjectName("actionSendViaMail")
        self.actionOpenHelpURL = QtWidgets.QAction(MainWindow)
        self.actionOpenHelpURL.setObjectName("actionOpenHelpURL")
        self.actionAddGDirve = QtWidgets.QAction(MainWindow)
        self.actionAddGDirve.setIconVisibleInMenu(False)
        self.actionAddGDirve.setObjectName("actionAddGDirve")
        self.actionRename = QtWidgets.QAction(MainWindow)
        self.actionRename.setIconVisibleInMenu(False)
        self.actionRename.setObjectName("actionRename")
        self.menu.addAction(self.actionAddFile)
        self.menu.addAction(self.actionAddGDirve)
        self.menu.addSeparator()
        self.menu.addAction(self.actionConvertToDisk)
        self.menu.addAction(self.actionSendToKindle)
        self.menu.addAction(self.actionSendViaMail)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSettings)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionOpenHelpURL)
        self.menu_2.addAction(self.actionOpenForumURL)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionAbout)
        self.menu_3.addAction(self.actionDelete)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionRename)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionViewLog)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.closeApp)
        self.actionAddFile.triggered.connect(MainWindow.addFilesAction)
        self.actionDelete.triggered.connect(MainWindow.deleteRecAction)
        self.actionOpenForumURL.triggered.connect(MainWindow.openSupportURL)
        self.actionViewLog.triggered.connect(MainWindow.openLog)
        self.actionAbout.triggered.connect(MainWindow.about)
        self.actionSettings.triggered.connect(MainWindow.settings)
        self.toolAdd.triggered.connect(MainWindow.addFilesAction)
        self.toolSettings.triggered.connect(MainWindow.settings)
        self.treeFileList.itemSelectionChanged.connect(MainWindow.changeBook)
        self.buttonSaveBookInfo.clicked.connect(MainWindow.saveBookInfo)
        self.toolInfo.triggered.connect(MainWindow.switchInfoPanel)
        self.toolSaveToDisk.triggered.connect(MainWindow.convertToDisk)
        self.toolSendToKindle.triggered.connect(MainWindow.sendToKindle)
        self.toolSendMail.triggered.connect(MainWindow.sendViaMail)
        self.actionConvertToDisk.triggered.connect(MainWindow.convertToDisk)
        self.actionSendToKindle.triggered.connect(MainWindow.sendToKindle)
        self.actionSendViaMail.triggered.connect(MainWindow.sendViaMail)
        self.actionOpenHelpURL.triggered.connect(MainWindow.openHelpURL)
        self.actionAddGDirve.triggered.connect(MainWindow.openFromGDrive)
        self.actionRename.triggered.connect(MainWindow.rename)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "fb2mobi"))
        self.treeFileList.headerItem().setText(0, _translate("MainWindow", "Title"))
        self.treeFileList.headerItem().setText(1, _translate("MainWindow", "Author"))
        self.treeFileList.headerItem().setText(2, _translate("MainWindow", "Series"))
        self.treeFileList.headerItem().setText(3, _translate("MainWindow", "Genre"))
        self.treeFileList.headerItem().setText(4, _translate("MainWindow", "File"))
        self.labelAuthor.setText(_translate("MainWindow", "Author"))
        self.labelBookTitle.setText(_translate("MainWindow", "Title"))
        self.labelSeries.setText(_translate("MainWindow", "Series"))
        self.labelSeriesNumber.setText(_translate("MainWindow", "#"))
        self.label.setText(_translate("MainWindow", "Genre"))
        self.labelBookLanguage.setText(_translate("MainWindow", "Book language"))
        self.label_2.setText(_translate("MainWindow", "Translator"))
        self.buttonSaveBookInfo.setText(_translate("MainWindow", "Save"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menu_2.setTitle(_translate("MainWindow", "Help"))
        self.menu_3.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAddFile.setText(_translate("MainWindow", "Add..."))
        self.actionAddFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpenForumURL.setText(_translate("MainWindow", "Support forum"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionViewLog.setText(_translate("MainWindow", "View log"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.toolAdd.setText(_translate("MainWindow", "Add"))
        self.toolInfo.setText(_translate("MainWindow", "Info"))
        self.toolSettings.setText(_translate("MainWindow", "Settings"))
        self.toolSaveToDisk.setText(_translate("MainWindow", "Convert to disk"))
        self.toolSaveToDisk.setToolTip(_translate("MainWindow", "Convert to disk"))
        self.toolSendToKindle.setText(_translate("MainWindow", "Send to Kindle"))
        self.toolSendMail.setText(_translate("MainWindow", "Send via Gmail"))
        self.actionConvertToDisk.setText(_translate("MainWindow", "Convert to disk"))
        self.actionSendToKindle.setText(_translate("MainWindow", "Send to Kindle"))
        self.actionSendViaMail.setText(_translate("MainWindow", "Send via Gmail"))
        self.actionOpenHelpURL.setText(_translate("MainWindow", "Help"))
        self.actionAddGDirve.setText(_translate("MainWindow", "Add from Google Drive..."))
        self.actionAddGDirve.setToolTip(_translate("MainWindow", "Add files from Google Drive.."))
        self.actionAddGDirve.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionRename.setText(_translate("MainWindow", "Rename..."))
        self.actionRename.setToolTip(_translate("MainWindow", "Rename selected files"))

