# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(546, 523)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboProfile = QtWidgets.QComboBox(self.tab)
        self.comboProfile.setObjectName("comboProfile")
        self.gridLayout_2.addWidget(self.comboProfile, 1, 0, 1, 1)
        self.comboFormat = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFormat.sizePolicy().hasHeightForWidth())
        self.comboFormat.setSizePolicy(sizePolicy)
        self.comboFormat.setObjectName("comboFormat")
        self.gridLayout_2.addWidget(self.comboFormat, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioHypYes = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioHypYes.sizePolicy().hasHeightForWidth())
        self.radioHypYes.setSizePolicy(sizePolicy)
        self.radioHypYes.setObjectName("radioHypYes")
        self.horizontalLayout.addWidget(self.radioHypYes)
        self.radioHypNo = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioHypNo.sizePolicy().hasHeightForWidth())
        self.radioHypNo.setSizePolicy(sizePolicy)
        self.radioHypNo.setObjectName("radioHypNo")
        self.horizontalLayout.addWidget(self.radioHypNo)
        self.radioHypProfile = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioHypProfile.sizePolicy().hasHeightForWidth())
        self.radioHypProfile.setSizePolicy(sizePolicy)
        self.radioHypProfile.setObjectName("radioHypProfile")
        self.horizontalLayout.addWidget(self.radioHypProfile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineDestFolder = QtWidgets.QLineEdit(self.tab)
        self.lineDestFolder.setObjectName("lineDestFolder")
        self.horizontalLayout_4.addWidget(self.lineDestFolder)
        self.btnSelectDestFolder = QtWidgets.QPushButton(self.tab)
        self.btnSelectDestFolder.setObjectName("btnSelectDestFolder")
        self.horizontalLayout_4.addWidget(self.btnSelectDestFolder)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboFont = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFont.sizePolicy().hasHeightForWidth())
        self.comboFont.setSizePolicy(sizePolicy)
        self.comboFont.setObjectName("comboFont")
        self.horizontalLayout_2.addWidget(self.comboFont)
        self.btnOpenFontsFolder = QtWidgets.QPushButton(self.tab)
        self.btnOpenFontsFolder.setObjectName("btnOpenFontsFolder")
        self.horizontalLayout_2.addWidget(self.btnOpenFontsFolder)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineKindlePath = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineKindlePath.setObjectName("lineKindlePath")
        self.horizontalLayout_3.addWidget(self.lineKindlePath)
        self.btnSelectKindlePath = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectKindlePath.sizePolicy().hasHeightForWidth())
        self.btnSelectKindlePath.setSizePolicy(sizePolicy)
        self.btnSelectKindlePath.setObjectName("btnSelectKindlePath")
        self.horizontalLayout_3.addWidget(self.btnSelectKindlePath)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.checkSyncCovers = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkSyncCovers.setObjectName("checkSyncCovers")
        self.verticalLayout_5.addWidget(self.checkSyncCovers)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineKindleDocsSubfolder = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineKindleDocsSubfolder.setObjectName("lineKindleDocsSubfolder")
        self.verticalLayout_5.addWidget(self.lineKindleDocsSubfolder)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineGoogleMail = QtWidgets.QLineEdit(self.groupBox)
        self.lineGoogleMail.setObjectName("lineGoogleMail")
        self.verticalLayout_2.addWidget(self.lineGoogleMail)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.lineGooglePassword = QtWidgets.QLineEdit(self.groupBox)
        self.lineGooglePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineGooglePassword.setObjectName("lineGooglePassword")
        self.verticalLayout_2.addWidget(self.lineGooglePassword)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.lineKindleMail = QtWidgets.QLineEdit(self.groupBox)
        self.lineKindleMail.setObjectName("lineKindleMail")
        self.verticalLayout_2.addWidget(self.lineKindleMail)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkWriteLog = QtWidgets.QCheckBox(self.tab_3)
        self.checkWriteLog.setObjectName("checkWriteLog")
        self.verticalLayout_4.addWidget(self.checkWriteLog)
        self.checkClearLogAfterExit = QtWidgets.QCheckBox(self.tab_3)
        self.checkClearLogAfterExit.setObjectName("checkClearLogAfterExit")
        self.verticalLayout_4.addWidget(self.checkClearLogAfterExit)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.comboLogLevel = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboLogLevel.sizePolicy().hasHeightForWidth())
        self.comboLogLevel.setSizePolicy(sizePolicy)
        self.comboLogLevel.setObjectName("comboLogLevel")
        self.comboLogLevel.addItem("")
        self.comboLogLevel.addItem("")
        self.comboLogLevel.addItem("")
        self.comboLogLevel.addItem("")
        self.verticalLayout_4.addWidget(self.comboLogLevel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        SettingsDialog.accepted.connect(SettingsDialog.closeAccept)
        self.btnSelectKindlePath.clicked.connect(SettingsDialog.selectKindlePath)
        self.btnOpenFontsFolder.clicked.connect(SettingsDialog.OpenFontsFolder)
        self.btnSelectDestFolder.clicked.connect(SettingsDialog.selectDestPath)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label.setText(_translate("SettingsDialog", "Profile"))
        self.label_2.setText(_translate("SettingsDialog", "Output format"))
        self.groupBox_3.setTitle(_translate("SettingsDialog", "Insert soft hyphens"))
        self.radioHypYes.setText(_translate("SettingsDialog", "Yes"))
        self.radioHypNo.setText(_translate("SettingsDialog", "No"))
        self.radioHypProfile.setText(_translate("SettingsDialog", "Profile default"))
        self.label_10.setText(_translate("SettingsDialog", "Destination folder"))
        self.btnSelectDestFolder.setText(_translate("SettingsDialog", "Select"))
        self.label_5.setText(_translate("SettingsDialog", "Embed font family"))
        self.btnOpenFontsFolder.setText(_translate("SettingsDialog", "Open fonts folder..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialog", "Converter"))
        self.groupBox_2.setTitle(_translate("SettingsDialog", "Send To Kindle"))
        self.label_4.setText(_translate("SettingsDialog", "Kindle mount point (if not detected on connect)"))
        self.btnSelectKindlePath.setText(_translate("SettingsDialog", "Select"))
        self.checkSyncCovers.setText(_translate("SettingsDialog", "Syncronize covers"))
        self.label_9.setText(_translate("SettingsDialog", "Place files in folder"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Send via Gmail"))
        self.label_3.setText(_translate("SettingsDialog", "Gmail address"))
        self.label_8.setText(_translate("SettingsDialog", "Gmail password"))
        self.label_7.setText(_translate("SettingsDialog", "Kindle address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsDialog", "Kindle"))
        self.checkWriteLog.setText(_translate("SettingsDialog", "Write log"))
        self.checkClearLogAfterExit.setText(_translate("SettingsDialog", "Clear log after exit"))
        self.label_6.setText(_translate("SettingsDialog", "Log level"))
        self.comboLogLevel.setItemText(0, _translate("SettingsDialog", "DEBUG"))
        self.comboLogLevel.setItemText(1, _translate("SettingsDialog", "INFO"))
        self.comboLogLevel.setItemText(2, _translate("SettingsDialog", "ERROR"))
        self.comboLogLevel.setItemText(3, _translate("SettingsDialog", "CRITICAL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingsDialog", "Log"))

